- pipeline.id: suumo_pipeline
  path.config: "/usr/share/logstash/pipeline/mongodb.conf"
  queue.type: persisted
- pipeline.id: test_pipeline
  path.config: "/usr/share/logstash/pipeline/logstash.conf"
  queue.type: persisted